[package]
name = "gaffa"
version = "0.5.1"
edition = "2024"
authors = ["<oryon@cyberise.de>"]
description = "Cross-platform process manager for Procfile-based process-collections."
license = "MIT"
repository = "https://github.com/oryon-dominik/interstellar-gaffa"
readme = "README.md"
keywords = ["procfile", "process-manager", "foreman", "overmind", "honcho"]
categories = [
    "command-line-utilities",
    "development-tools"
]

[[bin]]
name = "gaffa"
path = "src/bin/gaffa.rs"

[[test]]
name = "non_interactive_interrupt_test"
path = "tests/non_interactive_interrupt_test.rs"

[dependencies]
tokio = { version = "1.47.0", features = ["full"] }
colored = "3.0.0"
regex = "1"
shell-words = "1.1.0"
clap = { version = "4", features = ["derive"] }
thiserror = "2.0.12"
ratatui = "0.29"
crossterm = "0.29"
cli-clipboard = "0.4"
chrono = "0.4"
unicode-width = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "processenv", "winbase", "wincon", "handleapi", "jobapi2", "winnt", "processthreadsapi"] }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }

[package.metadata.docs.rs]
all-features = true

[badges]
github-actions = { repository = "oryon-dominik/interstellar-gaffa", branch = "trunk" }
